title: Mugisha Enock
description: Data/Business Analyst | Machine Learning Engineer
theme: jekyll-theme-minimal
show_downloads: true

# Navigation links
nav_links:
  - name: Home
    url: /
  - name: Resume
    url: /resume
  - name: Projects
    url: /projects
  - name: Contact
    url: /contact
  - name: Others
    url: /others
